### ISSUE TITLE
[1.x] Upgrade to PHP 8.2

### ISSUE THREAD

**Issue by imdhemy** [piscibus/siklid-api#257]
### Description

Upgrade to PHP 8.2

**Comment by Moemen-Gaballah** [comment]
After upgrading PHP version to 8.2 
php-cs-fixer gets an error because the PHP version 
when trying update php-cs-fixer to 3.16.0 
depend on another package (doctrine/annotations) want to upgrade it (from 1.14.3 to 2.0.0)
after trying to upgrade it gets another error because depends on another package (mongodb-odm-bundle) that wants  
doctrine/annotations version (1.14.3) and package is the latest version 


![Image](https://user-images.githubusercontent.com/31255104/230183934-ae8575fc-1902-4065-9531-42898f031b7a.png)


The image may be explained.
